MESSAGES:
  NO_PERMISSION: "&cYou dont have permission to perform this command."
  UPGRADE_CANCELLED: "&f[&bGuildCraft&f] &cYou have cancelled this upgrade."
  UPGRADE_COMPLETE: "&f[&bGuildCraft&f] &7You upgraded the &b%enchant% &7enchantment to &bLevel %new% &7for &b%cost% &7Tokens."
GUIS:
  PICKAXE_GUI:
    TITLE: "&fPickaxe Upgrades"
    ITEMS:
      ENABLE_COMING_SOON: true #if enabled coming soon enchantment items will be enabled.
      TOKENS:
        NAME: "&b&lPickaxe Tokens"
        SLOT: 2
        MATERIAL: "ENDER_EYE"
        GLOW: false
        LORE:
          - "&7Tokens are used as currency to purchase"
          - "&7pickaxe upgrade enchantments."
          - ""
          - "&7You can earn tokens by killing players or"
          - "&7from mining, the chance is randomly generated."
          - ""
          - "&7Tokens also have a small percentage to be"
          - "&7won with keys at &7&n/warp crates&7."
          - ""
          - "&7You have &b%tokens% &7tokens."
      PLAYER_PICKAXE:
        SLOT: 4
        UPGRADING_LORE_TEXT: "&c&l☣ &cYou are currently upgrading this pickaxe"
      INFORMATION:
        NAME: "&b&lUpgrade Information"
        SLOT: 6
        MATERIAL: "BLAZE_POWDER"
        GLOW: false
        LORE:
          - "&7You can purchase upgrades for a certain amount"
          - "&7of tokens, the price will change depending on"
          - "&7the type of upgrade."
          - ""
          - "&7Each enchantment has a maxiumum level to keep"
          - "&7the economy balanced."
          - ""
          - "&7Every upgrade completed is logged to prevent"
          - "&7any false reports."
      ENCHANTMENT_ITEM_FORMAT:
        NAME: "&b&l%enchantment%"
        MATERIAL: "BOOK"
        GLOW: false
        LORE:
          - ""
          - "&7%description%"
          - ""
          - "&b&l ┃ &7Current Level: &b%current%"
          - "&b&l ┃ &7Max Level: &b%max%"
          - "&b&l ┃ &7Upgrade Cost: &b%cost%"
          - ""
          - "&7Click to purchase this upgrade."
      ENCHANTMENT_ITEM_FORMAT_MAXIMUM:
        NAME: "&b&l%enchantment%"
        MATERIAL: "ENCHANTED_BOOK"
        GLOW: false
        LORE:
          - ""
          - "&7%description%"
          - ""
          - "&b&l ┃ &7Current Level: &b%current%"
          - "&b&l ┃ &7Max Level: &b%max%"
          - "&b&l ┃ &7Upgrade Cost: &bN/A"
          - ""
          - "&7You already have the maximum level of this enchant."
      MISC_ITEMS:
        PANE_1:
          ENABLED: false
          NAME: ""
          SLOT: 0
          MATERIAL: "STAINED_GLASS_PANE"
          GLOW: false
          LORE: []
  CONFIRM_GUI:
    TITLE: "&fUpgrade Confirmation"
    ITEMS:
      CANCEL_UPGRADE:
        NAME: "&c&lCancel Upgrade"
        MATERIAL: "RED_DYE"
        SLOT: 2
        GLOW: false
        LORE:
          - "&7Click to cancel this enchantment upgrade."
      PLAYER_PICKAXE:
        SLOT: 4
        UPGRADING_LORE_TEXT: "&c&l☣ &cYou are currently upgrading this pickaxe"
      INFORMATION:
        NAME: "&b&lUpgrade Information"
        SLOT: 6
        MATERIAL: "BOOK"
        GLOW: false
        LORE:
          - ""
          - "%description%"
          - ""
          - "&b&l ┃ &7Upgrade Cost: &b%cost%"
          - "&b&l ┃ &7Enchantment: &b%enchant% &7(%enchantname%)"
          - "&b&l ┃ &7New Level: &b%new%"
          - ""
          - "&7Click confirm to complete this upgrade."
      CONFIRM:
        NAME: "&aConfirm Upgrade"
        MATERIAL: "LIME_STAINED_GLASS_PANE"
        GLOW: false
        LORE:
          - ""
          - "&f&oThis will upgrade the enchantment on your pickaxe."
          - ""
          - "&b&l ┃ &7Upgrade Cost: &b%cost%"
          - "&b&l ┃ &7Enchantment: &b%enchant% &7(%enchantname%)"
          - "&b&l ┃ &7New Level: &b%new%"
          - ""
          - "&c&lNOTE: &fThe upgrade process is automatic and"
          - "&flogged, upgrades cannot be reversed."
          - ""
          - "&7Click to confirm this upgrade."
        SLOTS:
          - 10
          - 11
          - 12
          - 19
          - 20
          - 21
          - 28
          - 29
          - 30
      CANCEL:
        NAME: "&cCancel Upgrade"
        MATERIAL: "RED_STAINED_GLASS_PANE"
        GLOW: false
        LORE:
          - "&7Click to cancel this enchantment upgrade."
        SLOTS:
          - 14
          - 15
          - 16
          - 23
          - 24
          - 25
          - 32
          - 33
          - 34

